# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 回锅录
subtitle: 学习 & 探索
description: 不变初心，特立独行。
keywords:
author: 回锅肉
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://hyperscalar.github.io/zh
root: /zh/
permalink: posts/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
- README.md
- 404.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  pagination_dir: page

category_generator:
  per_page: 10
  order_by: -date

tag_generator:
  per_page: 10
  order_by: -date

archive_generator:
  enabled: true
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -date

alias:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

## Feed: https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: false
  hub:
  content:
  content_limit:
  content_limit_delim:
  order_by: -date
  icon:

## Sitemap: https://github.com/hexojs/hexo-generator-sitemap
sitemap:
    path: sitemap.xml
    template: ./sitemap-template.xml
    rel: false

## Nofollow: https://github.com/hexojs/hexo-filter-nofollow
nofollow:
  enable: true
  field: site
  exclude:

# Server: https://github.com/hexojs/hexo-server
server:
  port: 4040
  log: true
  ip: 127.0.0.1
  compress: false
  header: true
  serveStatic:
    extensions:
    - html

# Extensions
## Plugins: https://hexo.io/plugins/

## Markdown-it: https://github.com/hexojs/hexo-renderer-markdown-it/
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  anchors:
    # Minimum level for ID creation. (Ex. h2 to h6)
    level: 1
    # A suffix that is prepended to the number given if the ID is repeated.
    collisionSuffix: ''
    # If `true`, creates an anchor tag with a permalink besides the heading.
    permalink: true
    # Class used for the permalink anchor tag.
    permalinkClass: header-anchor
    # Set to 'right' to add permalink after heading
    permalinkSide: 'left'
    # The symbol used to make the permalink
    permalinkSymbol: ¶
    # Transform anchor to (1) lower case; (2) upper case
    case: 0
    # Replace space with a character
    separator: '-'
  plugins:
    - markdown-it-abbr
    - markdown-it-cjk-breaks
    - markdown-it-container
    - markdown-it-deflist
    - markdown-it-emoji
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-mark
    - markdown-it-sub
    - markdown-it-sup

## Math: https://github.com/hexojs/hexo-math
math:
  mathjax:
    options:
      conversion:
        display: false
  katex:
    options:
      displayMode: false
      throwOnError: false

## Stylus: https://github.com/hexojs/hexo-renderer-stylus
stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .
  plugins: 'nib'

## Search: https://github.com/theme-next/hexo-generator-searchdb
search:
  path: search.xml
  field: all
  content: true
  format: html

## Symbols count: https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false
  awl: 2
  wpm: 300
  suffix: "mins."

## Themes: https://hexo.io/themes/
theme: next
